sudo: true
dist: trusty

language: node_js

node_js:
  - "8.11.4"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - clang-3.5


before_install:
  - if [[ $(uname -s) == 'Linux' ]]; then
       export CXX="clang++-3.5";
       export CC="clang-3.5";
    fi;
  - npm conf set strict-ssl false
  - npm install -g npm@6.4.0
  - export DISPLAY=:99
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"


install:
  - cd test
  - npm i --clang=1
  - cd ..


script:
  - cd test
  - npm test
  - cd ..
