name: Build Windows

on:
  workflow_dispatch

jobs:
  Build:
    if: contains('["raub"]', github.actor)
    runs-on: windows-2022

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: windows-${{ github.run }}-${{ github.sha }}
          name: Windows
          body: Windows binaries at ${{ github.sha }}
          files: src/build/Release/webgl.node
